### PR TITLE
Update python minor versions and upgrade pip to the latest 20.2.3

### PR DESCRIPTION
**Pull request by amCap1712**

### CODE REVIEW

**Comment by alastair** [comment]
Thanks, Can you do this for all python versions (including 2.7 [AB, sir])?  Later, we should do another PR to add 3.9 and remove 3.5 and 3.6 (as long as all projects are upgraded)

**Comment by amCap1712** [comment]
I have upgraded pip and the point versions of python releases in the repository. I checked and found that Python 3.5 already been removed from the repository and [livegrep](http://livegrep.metabrainz.org/search/livegrep?q=FROM%20metabrainz%2Fpython%3A3.5&fold_case=auto&regex=true&context=true&repo%5B%5D=metabrainz%2F.github&repo%5B%5D=metabrainz%2F3scale-vcl&repo%5B%5D=metabrainz%2FCAA-indexer&repo%5B%5D=metabrainz%2FCAA-spec&repo%5B%5D=metabrainz%2FCoverArtArchive&repo%5B%5D=metabrainz%2FMBS-211-spec&repo%5B%5D=metabrainz%2FMusicBrainz-R2RML&repo%5B%5D=metabrainz%2Facousticbrainz-android&repo%5B%5D=metabrainz%2Facousticbrainz-dataset-runner&repo%5B%5D=metabrainz%2Facousticbrainz-server&repo%5B%5D=metabrainz%2Fartist-artist-relations&repo%5B%5D=metabrainz%2Fbase-image&repo%5B%5D=metabrainz%2Fbm&repo%5B%5D=metabrainz%2Fbrainzutils-python&repo%5B%5D=metabrainz%2Fcaa-admin&repo%5B%5D=metabrainz%2Fchanged-mbid-feed&repo%5B%5D=metabrainz%2Fchef-cookbooks&repo%5B%5D=metabrainz%2Fcoverart_redirect&repo%5B%5D=metabrainz%2Fcritiquebrainz&repo%5B%5D=metabrainz%2Fdata-set-hoster&repo%5B%5D=metabrainz%2Fdbmirror&repo%5B%5D=metabrainz%2Fdesign-system&repo%5B%5D=metabrainz%2Fdiscourse-musicbrainz-auth&repo%5B%5D=metabrainz%2Fdjcaa&repo%5B%5D=metabrainz%2Fdocker-angelfish&repo%5B%5D=metabrainz%2Fdocker-anon-ftp&repo%5B%5D=metabrainz%2Fdocker-consul-template-base&repo%5B%5D=metabrainz%2Fdocker-exim&repo%5B%5D=metabrainz%2Fdocker-helpers&repo%5B%5D=metabrainz%2Fdocker-irccat&repo%5B%5D=metabrainz%2Fdocker-node&repo%5B%5D=metabrainz%2Fdocker-openresty&repo%5B%5D=metabrainz%2Fdocker-piwik&repo%5B%5D=metabrainz%2Fdocker-postgres&repo%5B%5D=metabrainz%2Fdocker-python&repo%5B%5D=metabrainz%2Fdocker-redis&repo%5B%5D=metabrainz%2Fdocker-rsyncd&repo%5B%5D=metabrainz%2Fdocker-sshd&repo%5B%5D=metabrainz%2Fdump-scripts&repo%5B%5D=metabrainz%2Fgeordi&repo%5B%5D=metabrainz%2Fguidelines&repo%5B%5D=metabrainz%2Fhadoop-cluster-docker&repo%5B%5D=metabrainz%2Fjenkins&repo%5B%5D=metabrainz%2Flibcoverart&repo%5B%5D=metabrainz%2Flibdiscid&repo%5B%5D=metabrainz%2Flibmusicbrainz&repo%5B%5D=metabrainz%2Flistenbrainz-server&repo%5B%5D=metabrainz%2Flobes&repo%5B%5D=metabrainz%2Flocustfiles&repo%5B%5D=metabrainz%2Flogster&repo%5B%5D=metabrainz%2Fmb-rngpy&repo%5B%5D=metabrainz%2Fmb-solr&repo%5B%5D=metabrainz%2Fmb2wikidatabot&repo%5B%5D=metabrainz%2Fmbs_logs_parsers&repo%5B%5D=metabrainz%2Fmbspotify&repo%5B%5D=metabrainz%2Fmbsssss&repo%5B%5D=metabrainz%2Fmbstats&repo%5B%5D=metabrainz%2Fmessybrainz-labs&repo%5B%5D=metabrainz%2Fmessybrainz-server&repo%5B%5D=metabrainz%2Fmetabrainz-howto-guides&repo%5B%5D=metabrainz%2Fmetabrainz-logos&repo%5B%5D=metabrainz%2Fmetabrainz.org&repo%5B%5D=metabrainz%2Fmiscellaneous&repo%5B%5D=metabrainz%2Fmlhd-import&repo%5B%5D=metabrainz%2Fmmd-schema&repo%5B%5D=metabrainz%2Fmodbot&repo%5B%5D=metabrainz%2Fmusicbrainz-android&repo%5B%5D=metabrainz%2Fmusicbrainz-data&repo%5B%5D=metabrainz%2Fmusicbrainz-data-service&repo%5B%5D=metabrainz%2Fmusicbrainz-docker&repo%5B%5D=metabrainz%2Fmusicbrainz-email&repo%5B%5D=metabrainz%2Fmusicbrainz-logs&repo%5B%5D=metabrainz%2Fmusicbrainz-logs-cookbooks&repo%5B%5D=metabrainz%2Fmusicbrainz-server&repo%5B%5D=metabrainz%2Fmusicbrainz-server-log-analysis&repo%5B%5D=metabrainz%2Fmusicbrainz-survey&repo%5B%5D=metabrainz%2Fmusicbrainz-vm&repo%5B%5D=metabrainz%2Fnewhost-replication-fix&repo%5B%5D=metabrainz%2Fnotification-server&repo%5B%5D=metabrainz%2Fpicard&repo%5B%5D=metabrainz%2Fpicard-plugin-tools&repo%5B%5D=metabrainz%2Fpicard-website&repo%5B%5D=metabrainz%2Fpostgresql-musicbrainz-collate&repo%5B%5D=metabrainz%2Fpostgresql-musicbrainz-unaccent&repo%5B%5D=metabrainz%2Fratelimit-server&repo%5B%5D=metabrainz%2Fsearch-indexer&repo%5B%5D=metabrainz%2Fsearch-server&repo%5B%5D=metabrainz%2Fsir&repo%5B%5D=metabrainz%2Fspambrainz&repo%5B%5D=metabrainz%2Fspambrainz_ml&repo%5B%5D=metabrainz%2Fsys-tools&repo%5B%5D=metabrainz%2Ftelegraf-docker&repo%5B%5D=metabrainz%2Ftomcat-service&repo%5B%5D=metabrainz%2Ftroi-recommendation-playground&repo%5B%5D=metabrainz%2Fvagrant-images&repo%5B%5D=metabrainz%2Fweb-service-v3-design&repo%5B%5D=metabrainz%2Fxmpp-messaging-server) shows thats only brainzutils is using it. So, let's add 3.9 and update it to 3.9 directly.

**Review by alastair — APPROVED** [review]
This is good. After a discussion with @mayhem we decided to start releasing python base images with a date in the version, which means that each project can upgrade in their own time. I'll add this

**Review by yvanzo — APPROVED** [review]
I tagged current images with the creation date, see: https://hub.docker.com/r/metabrainz/python/tags
I will open a pull request to follow the same tagging scheme using `push.sh`.

**Pull request merged**
